---
# tasks file for ansible-role-postgres

- name: Define var postgres_version_no_dots. e.g. if 9.4 >> 94
  set_fact:
    postgres_version_no_dots: "{{ postgres_version | regex_replace('\\.') }}"

- name: Install the postgres repos
  yum:
    name: "{{ postgres_yum_repos_rpm }}"
    state: present

- name: Install postgres rpms
  yum:
    name: "{{ postgres_packages }}"
    state: present

- name: Check if postgres has been initialized
  stat:
    path: "/var/lib/pgsql/{{ postgres_version }}/initdb.log"
  register: postgres_initialized

- name: Initialize postgres
  command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql{{ postgres_version_no_dots }}-setup initdb"
  when: not postgres_initialized.stat.exists

- name: Start and enable the postgres service
  service:
    name: "postgresql-{{ postgres_version }}"
    state: started
    enabled: yes

...
